### ISSUE TITLE
Output of DeepFM layer

### ISSUE THREAD

**Issue by brendk** [Jeondanin/predict-by-fa-cnn#1]
Hi, I've found your repository as I'm looking to reproduce the same paper. Great work!
Have you been able to integrate the output of the DeepFM layer with the Attention Network?
I managed to get both layers to work separately:
- For the DeepFM, input tensor shape [8760, 32] (with x.to(torch.int64)), output shape [8760]
- For the Attention Network, input tensor shape [1, 1, 8760, 32], output shape [1, 32, 8760, 1]
But I'm not sure how to integrate both outputs to pass them to the final fully connected layer.
Also, what does 8760 refer to in your code? Are you concatenating daily data from multiple stocks?
Would love to know your thoughts on this!
Thanks

**Comment by Jeondanin** [comment]
sorry. Actually I tried to implement  that paper, I have worked for other thing. 

well.. how about adjusting DeepFm input tensor to [8760, 32, x] for making output shape [8760, x]? 
even I don't know how it wrote about DeepFm, Adjusting input tensor or output shape may be a key of your question.

Thanks. let me close this issue.
